//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Behlog.Cms.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Behlog.Cms.Resources.EnumText", typeof(EnumText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بایگانی.
        /// </summary>
        public static string Archived {
            get {
                return ResourceManager.GetString("Archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اچ.تی.ام.ال.
        /// </summary>
        public static string BodyType_HTML {
            get {
                return ResourceManager.GetString("BodyType_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مارک داون.
        /// </summary>
        public static string BodyType_Markdown {
            get {
                return ResourceManager.GetString("BodyType_Markdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوشته ساده.
        /// </summary>
        public static string BodyType_Text {
            get {
                return ResourceManager.GetString("BodyType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پذیرفته شده.
        /// </summary>
        public static string Comment_Approved {
            get {
                return ResourceManager.GetString("Comment_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسدود شده.
        /// </summary>
        public static string Comment_Blocked {
            get {
                return ResourceManager.GetString("Comment_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مردود.
        /// </summary>
        public static string Comment_Rejected {
            get {
                return ResourceManager.GetString("Comment_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هرز نظر.
        /// </summary>
        public static string Comment_Spam {
            get {
                return ResourceManager.GetString("Comment_Spam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان بندی شده.
        /// </summary>
        public static string Content_Planned {
            get {
                return ResourceManager.GetString("Content_Planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتشر شده.
        /// </summary>
        public static string Content_Published {
            get {
                return ResourceManager.GetString("Content_Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد شده.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف شده.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیرفعال.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش نویس.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استفاده شده.
        /// </summary>
        public static string File_Attached {
            get {
                return ResourceManager.GetString("File_Attached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صدا.
        /// </summary>
        public static string FileType_Audio {
            get {
                return ResourceManager.GetString("FileType_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمومی.
        /// </summary>
        public static string FileType_Common {
            get {
                return ResourceManager.GetString("FileType_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشرده.
        /// </summary>
        public static string FileType_CompressedArchive {
            get {
                return ResourceManager.GetString("FileType_CompressedArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند.
        /// </summary>
        public static string FileType_Document {
            get {
                return ResourceManager.GetString("FileType_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلودها.
        /// </summary>
        public static string FileType_Downloads {
            get {
                return ResourceManager.GetString("FileType_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر.
        /// </summary>
        public static string FileType_Image {
            get {
                return ResourceManager.GetString("FileType_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ناشناخته.
        /// </summary>
        public static string FileType_Unknown {
            get {
                return ResourceManager.GetString("FileType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویدئو.
        /// </summary>
        public static string FileType_Video {
            get {
                return ResourceManager.GetString("FileType_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخفی.
        /// </summary>
        public static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال تعمیر.
        /// </summary>
        public static string UnderConstruction {
            get {
                return ResourceManager.GetString("UnderConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ناشناخته!.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسته شده.
        /// </summary>
        public static string Website_Closed {
            get {
                return ResourceManager.GetString("Website_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آفلاین.
        /// </summary>
        public static string Website_Offline {
            get {
                return ResourceManager.GetString("Website_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آنلاین.
        /// </summary>
        public static string Website_Online {
            get {
                return ResourceManager.GetString("Website_Online", resourceCulture);
            }
        }
    }
}
