//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Behlog.Cms.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Behlog.Cms.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website&apos;s Status is invalid..
        /// </summary>
        public static string webiste_status_invalid {
            get {
                return ResourceManager.GetString("webiste.status.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website&apos;s Copyright text MaxLen.
        /// </summary>
        public static string website_cpr_maxlen {
            get {
                return ResourceManager.GetString("website.cpr.maxlen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website&apos;s Description MaxLen .
        /// </summary>
        public static string website_desc_maxlen {
            get {
                return ResourceManager.GetString("website.desc.maxlen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website&apos;s Email format is not valid..
        /// </summary>
        public static string website_email_format {
            get {
                return ResourceManager.GetString("website.email.format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website&apos;s Keywords MaxLen.
        /// </summary>
        public static string website_keywords_maxlen {
            get {
                return ResourceManager.GetString("website.keywords.maxlen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website&apos;s Name MaxLen is 256..
        /// </summary>
        public static string website_name_maxlen {
            get {
                return ResourceManager.GetString("website.name.maxlen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website&apos;s Name cannot be null or empty..
        /// </summary>
        public static string website_name_null {
            get {
                return ResourceManager.GetString("website.name.null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website&apos;s Owner UserId is null..
        /// </summary>
        public static string website_owneruser_null {
            get {
                return ResourceManager.GetString("website.owneruser.null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website&apos;s Title MaxLen is 256.
        /// </summary>
        public static string website_title_maxlen {
            get {
                return ResourceManager.GetString("website.title.maxlen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website&apos;s Title cannot be null..
        /// </summary>
        public static string website_title_null {
            get {
                return ResourceManager.GetString("website.title.null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website&apos;s Url MaxLen.
        /// </summary>
        public static string website_url_maxlen {
            get {
                return ResourceManager.GetString("website.url.maxlen", resourceCulture);
            }
        }
    }
}
