//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Behlog.Cms.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationErrorCodes {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrorCodes() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Behlog.Cms.Resources.ValidationErrorCodes", typeof(ValidationErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string website_name_null {
            get {
                return ResourceManager.GetString("website.name.null", resourceCulture);
            }
        }
        
        internal static string website_title_null {
            get {
                return ResourceManager.GetString("website.title.null", resourceCulture);
            }
        }
        
        internal static string website_owneruser_null {
            get {
                return ResourceManager.GetString("website.owneruser.null", resourceCulture);
            }
        }
        
        internal static string website_name_maxlen {
            get {
                return ResourceManager.GetString("website.name.maxlen", resourceCulture);
            }
        }
        
        internal static string website_title_maxlen {
            get {
                return ResourceManager.GetString("website.title.maxlen", resourceCulture);
            }
        }
    }
}
